use super::MurInjects;
use crate::MurServiceContainer;
use std::any::Any;

/// Core trait for singleton and scoped services managed by the DI container.
///
/// Implement `MurService` on any type that should be registered with
/// [`MurServiceContainer`] and injected into controllers, guards,
/// interceptors, or other services.
///
/// The `#[service]` or `#[injectable]` derive macros generate the required
/// boilerplate automatically.
///
/// # Example
///
/// ```rust,ignore
/// #[service]
/// struct DatabaseService {
///     pool: Arc<Pool>,
/// }
///
/// impl MurService for DatabaseService {
///     fn as_any(&self) -> &dyn Any { self }
/// }
/// ```
pub trait MurService: Send + Sync + 'static {
	/// Returns a type-erased reference used for runtime downcasting in the container.
	fn as_any(&self) -> &dyn Any;

	/// Called once when the service is first resolved from the container.
	///
	/// Override to run initialization logic such as establishing connections.
	fn on_init(&self) {}

	/// Called when the server is shutting down.
	///
	/// Override to release resources (close connections, flush buffers, etc.).
	fn on_shutdown(&self) {}
}

/// Dependency-injection factory for [`MurService`] implementations.
///
/// Generated by the `#[service]` macro. The framework calls `__create_factory`
/// when building the service instance during server startup.
pub trait MurServiceFactory: MurService {
	/// Constructs the service using dependencies from `injects` and `container`.
	fn __create_factory(injects: &MurInjects, _container: &MurServiceContainer) -> Self;
}

/// Trait for values that can be manually injected into the DI container
/// without participating in the full service lifecycle.
///
/// `MurInjectable` is the lightweight counterpart to [`MurService`]. Use it
/// for configuration objects, external clients, or shared state that must be
/// available across controllers but does not need `on_init` / `on_shutdown`
/// hooks.
pub trait MurInjectable: Send + Sync + 'static {
	/// Returns a type-erased reference used for runtime downcasting.
	fn as_any(&self) -> &dyn Any;

	/// Called when the injectable is first registered.
	fn on_init(&self) {}

	/// Called during server shutdown.
	fn on_shutdown(&self) {}
}
