mod analyze_parameter;
mod extract_arc_inner;
mod extract_generic_type;
mod extract_option_inner;
mod gen_constructor;
mod gen_deps_impl;
mod gen_parsed_impl_args;
mod has_self;
mod infer_inject_from_field;
mod is_constructor;
mod normalize_manual_inject;
mod normalize_path;
mod require_self_params;

pub use analyze_parameter::analyze_parameter;
pub use extract_arc_inner::extract_arc_inner;
pub use extract_generic_type::extract_generic_type;
pub use extract_option_inner::extract_option_inner;
pub use gen_constructor::gen_constructor;
pub use gen_deps_impl::gen_deps_impl;
pub use gen_parsed_impl_args::gen_parsed_impl_args;
pub use has_self::has_self;
pub use infer_inject_from_field::infer_injects_from_fields;
pub use is_constructor::is_constructor;
pub use normalize_manual_inject::InjectSpec;
pub use normalize_manual_inject::normalize_manual_inject;
pub use normalize_path::normalize_path;
pub use require_self_params::require_self_params;

use crate::types::{ParamInfo, ParamKind};
